// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.33.1
// source: physiosim/v1/engine.proto

package enginepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SimulationEngine_RunSimulation_FullMethodName = "/physiosim.v1.SimulationEngine/RunSimulation"
)

// SimulationEngineClient is the client API for SimulationEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SimulationEngineClient interface {
	RunSimulation(ctx context.Context, in *SimulationRequest, opts ...grpc.CallOption) (*SimulationResponse, error)
}

type simulationEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewSimulationEngineClient(cc grpc.ClientConnInterface) SimulationEngineClient {
	return &simulationEngineClient{cc}
}

func (c *simulationEngineClient) RunSimulation(ctx context.Context, in *SimulationRequest, opts ...grpc.CallOption) (*SimulationResponse, error) {
	out := new(SimulationResponse)
	err := c.cc.Invoke(ctx, SimulationEngine_RunSimulation_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SimulationEngineServer is the server API for SimulationEngine service.
// All implementations must embed UnimplementedSimulationEngineServer
// for forward compatibility
type SimulationEngineServer interface {
	RunSimulation(context.Context, *SimulationRequest) (*SimulationResponse, error)
	mustEmbedUnimplementedSimulationEngineServer()
}

// UnimplementedSimulationEngineServer must be embedded to have forward compatible implementations.
type UnimplementedSimulationEngineServer struct {
}

func (UnimplementedSimulationEngineServer) RunSimulation(context.Context, *SimulationRequest) (*SimulationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunSimulation not implemented")
}
func (UnimplementedSimulationEngineServer) mustEmbedUnimplementedSimulationEngineServer() {}

// UnsafeSimulationEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SimulationEngineServer will
// result in compilation errors.
type UnsafeSimulationEngineServer interface {
	mustEmbedUnimplementedSimulationEngineServer()
}

func RegisterSimulationEngineServer(s grpc.ServiceRegistrar, srv SimulationEngineServer) {
	s.RegisterService(&SimulationEngine_ServiceDesc, srv)
}

func _SimulationEngine_RunSimulation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimulationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulationEngineServer).RunSimulation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimulationEngine_RunSimulation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulationEngineServer).RunSimulation(ctx, req.(*SimulationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SimulationEngine_ServiceDesc is the grpc.ServiceDesc for SimulationEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SimulationEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "physiosim.v1.SimulationEngine",
	HandlerType: (*SimulationEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunSimulation",
			Handler:    _SimulationEngine_RunSimulation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "physiosim/v1/engine.proto",
}
